/**:
  ros__parameters:
    # min_longitudinal_offset: 1.8
    # min_longitudinal_offset: 0.0
    min_longitudinal_offset: -1.0
    max_longitudinal_offset: 0.8
    min_lateral_offset: -1.4
    max_lateral_offset: 1.4
    # min_height_offset: 0.8
    min_height_offset: -0.2
    max_height_offset: 1.5
