/**:
  ros__parameters:
    wheel_radius: 0.1878
    wheel_width: 0.037
    wheel_base: 0.337 # between front wheel center and rear wheel center
    wheel_tread: 0.630 # between left wheel center and right wheel center
    front_overhang: 0.432 # between front wheel center and vehicle front
    rear_overhang: 0.331 # between rear wheel center and vehicle rear
    left_overhang: 0.07 # between left wheel center and vehicle left
    right_overhang: 0.07 # between right wheel center and vehicle right
    vehicle_height: 1.054 # vehicle height + sensor_kit height
    max_steer_angle: 0.70 # [rad]
